Dockerfile

These are required to build binary packages for python 3.

Include python 3.4 dev headers

---

Dockerfile

Adding PYTHONUNBUFFERED

---

Dockerfile

The newest debian images for jessie (gcr.io/google-appengine/debian8:latest) now has all the extra env variables and ca-certs that were in base.
cc @dlorenc

Switch base image from base to debian8

---

.gitignore
Dockerfile
Makefile
cloudbuild.yaml.in
python-interpreter-builder/Makefile

Ref #29 #35 
cc @duggelz 
This version is a lot simpler but it builds the interpreter each time and takes about 35 minutes to run.

Second version of switching things to cloud build.

---

Makefile
jenkins_build.sh

Docker 1.12 removed support for the "-f" flag to "docker tag".
Replace it with code that should work for at least Docker 1.09 and
above.

Fix "docker tag" usage for Docker 1.12

---

cloudbuild.yaml.in

this will ensure security updates are picked up in the cloud build.

prevent container build from using cached images

---

Makefile

I will separately add something to README.md describing how to invoke make to rebuild the image.

Require explicit IMAGE_NAME to avoid errors and confusion.

---

Makefile
README.md
cloudbuild.yaml.in
jenkins_build.sh
system_tests/Makefile
tests/Makefile
tests/google-cloud-python/Dockerfile.in

All targets using the Google Container Builder are prefixed with 'cloud-' and all targets that use the local Docker daemon are prefixed with 'local-'.
The google-cloud-python system tests will be addressed in later change.

Reorganize the Makefile and add documentation for building the image

---

tests/integration/server.py

These changes update the integration testing sample application to conform to the newest updates to the framework, seen in https://github.com/GoogleCloudPlatform/runtimes-common/pull/125.
@dlorenc @duggelz

add support for testing logging through standard module and custom client

---

tests/python2-libraries/requirements.txt

'pip install distribute' unpredictably fails when other packages are
being updated at the same time.  See
https://github.com/pypa/setuptools/issues/535 for related discussion.
Error message looks like:
Running setup.py install for distribute: started
Running setup.py install for distribute: finished with status 'error'
Complete output from command /env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-9DiKZ8/distribute/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-zFa039-record/install-record.txt --single-version-externally-managed --compile --install-headers /env/include/site/python2.7/distribute:
running install
running build
running …

Remove 'distribute' from library test.

---

RELEASING.md
build.sh
tests/google-cloud-python-system/Dockerfile.in

The previous behavior could possibly, conceivably be causing problems.
Now, the user now specifies GOOGLE_CLOUD_PROJECT_FOR_TESTS, which
should not collide with anything, and the GOOGLE_CLOUD_PROJECT
environment variable is only set for the single thing that should need
it, which is run_system_tests.sh, and only in the single, ephemeral
Docker container where we run those system tests.

Change handling of GOOGLE_CLOUD_PROJECT in build.sh.

---

tests/benchmark/Dockerfile.in

The new benchmark suite runs experiment on 54 Python functions while the previous one runs on 10 functions. So it took much longer for the new benchmark to complete and sometimes causes time-out issue. To solve this, I added the --debug-single-value flag to the command which runs single experiment per function so the benchmark can complete faster. The only concern is that the result for comparison using single value is not stable, an alternative approach might be specifying which functions we want to do experiments on instead of on all of the 54 functions.
Tested on gcr.io/cloud-python-runtime-qa.
Command:
DOCKER_NAMESPACE=gcr.io/cloud-python-runtime-qa TAG=latest ./build.sh --nobuild --benchmark
Result (partial):

Updated the benchmark code to migrate to the new Python benchmark suite

---

RELEASING.md
tests/benchmark/Dockerfile.in
tests/benchmark/benchmark_between_releases.sh

Added code to benchmark the same interpreter from release to release. The workflow is that first build image for release1 and release2, then do docker cp to get the benchmark json files from the image to host. And finally do pyperformance compare on the json files. Then the result of comparing python versions for the two releases are stored as files on host named as py2.7_res, py3.4_res and py3.5_res.
Test completed.
Command: DOCKER_NAMESPACE=gcr.io/google-appengine TAG1=2017-02-28_19_33 TAG2=2017-04-07-115536 ./benchmark_between_releases.sh
Usage: cd to tests/benchmark/benchmark_between_releases/ and run the shell script.

Benchmark the same interpreter from release to release.

---

tests/benchmark/Dockerfile.in
tests/benchmark/benchmark_between_releases.sh
tests/benchmark/generate_csv.py

Design doc: https://docs.google.com/document/d/1hWhbGl_15IFNDdc2x-d4Xdb4w0jzxWA55Gf6L8EPyt0/edit
Dashboard: go/python-benchmark-dashboard
Using cloud project cloud-python-runtime-qa
Added checks to skip benchmarking python3.6 if not available in the image.

Implemented the benchmark dashboard

---

cloudbuild.yaml
python-interpreter-builder/Dockerfile.in
python-interpreter-builder/scripts/build-python-3.5.sh
python-interpreter-builder/scripts/build-python-3.6.sh
tests/virtualenv/virtualenv_python34.yaml
tests/virtualenv/virtualenv_python35.yaml
tests/virtualenv/virtualenv_python36.yaml

Adding Python 3.6 made the image grow to more than 1GB.  This reduces the image back down to 770MB.

Remove unused files to make the Docker image smaller

---

README.md

This brings it up to date with official documentation: https://cloud.google.com/appengine/docs/flexible/python/runtime

Replace deprecated "vm: true" in app.yaml example with "env: flex"

---

build.sh
cloudbuild.yaml

The canonical builder image will be `gcr.io/gcp-runtimes/python/gen-dockerfile`

Rename builder image to parallel the other languages' builders.

---

scripts/gen_dockerfile.py
scripts/gen_dockerfile_test.py

In some cases, gcloud sets an environment variable to indicate
the location of the application configuration file, rather than
using the --config flag.

Allow $GAE_APPLICATION_YAML_PATH as an alternative to --config

---

cloudbuild_library_tests.yaml

Timeout was 10 minutes, now is 30 minutes.  Build currently takes about 20 minutes.

Increase timeout for library compatibility test

---

perf-dashboard/clientlibs-download/python_clientlibs_download.py

The bigquery client library deprecated `QueryJob.results()` recently.

Update the dashboard script to match the bigquery library changes

---

python-interpreter-builder/Dockerfile.in

The `patches` directory was implicitly removed in #142 when we deleted the last file in it.  However, this wasn't found in testing because my local client still had a patches directory.

Fix Dockerfile reference to deleted directory.

---

perf-dashboard/clientlibs-download/python_clientlibs_download.py

This is for fixing the build failure.

Update bigquery method to match the latest version

---

tests/integration/requirements.txt

It was using a too-old version of six in some cases, leading to this error:
```  
File "/usr/local/lib/python2.7/dist-packages/google/api/core/exceptions.py", line 43, in <module>
@six.python_2_unicode_compatible
AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'
```

Add missing dependency

---

cloudbuild_test.yaml
tests/python2-libraries/Dockerfile
tests/python2-libraries/python2-libraries.yaml
tests/python3-libraries/Dockerfile
tests/python3-libraries/python3-libraries.yaml
tests/virtualenv/virtualenv_default.yaml
tests/virtualenv/virtualenv_python34.yaml
tests/virtualenv/virtualenv_python35.yaml
tests/virtualenv/virtualenv_python36.yaml

This moves the structure tests to run on the latest version (**v0.1.1**) of the [container-structure-test](https://github.com/GoogleCloudPlatform/container-structure-test) framework. The newest version removes the concept of a test "state", meaning every test is run in isolation; this means we need to run setup commands on each individual command, rather than relying on test ordering in the config.
Additionally, the framework itself does not run the test image as a docker container inside itself anymore, meaning we can't reference external files (namely, `/workspace`). To work around this, I built small intermediate images based on the image under test that copy in necessary files for the tests that needed them.
This should have no functional change to the build.

Migrate structure tests to new version

---

cloudbuild_test.yaml
runtime-image/Dockerfile.in
runtime-image/resources/requirements-virtualenv.txt
runtime-image/resources/requirements.txt
tests/no-virtualenv/no-virtualenv.yaml
tests/python2-libraries/python2-libraries.yaml
tests/virtualenv/virtualenv_default.yaml
tests/virtualenv/virtualenv_python27.yaml
tests/virtualenv/virtualenv_python34.yaml
tests/virtualenv/virtualenv_python35.yaml
tests/virtualenv/virtualenv_python36.yaml

A previous change (#161) caused the 'virtualenv' command change to switch its
default Python version from 2.7 to 3.6 (when no -p flag is passed).
Although not a bad change, it was accidental, and this reverts to the
previous behavior.  This also add tests for the behavior, and fixes
various tests that had been subtly broken by a previous refactoring.
The cause of this behavior change was that the 'virtualenv' package
was installed under each Python interpreter, instead of the 'wheel'
package.

Revert to previous virtualenv behavior.

---

python-interpreter-builder/scripts/build-python-3.5.sh
python-interpreter-builder/scripts/build-python-3.6.sh

Building python interpreter failed at test_xmlrpc_net, error message as below:
```
ERROR: test_python_builders (test.test_xmlrpc_net.PythonBuildersTest)
Step #0: ----------------------------------------------------------------------
Step #0: Traceback (most recent call last):
Step #0:   File "/opt/sources/Python-3.5.4/Lib/test/test_xmlrpc_net.py", line 17, in test_python_builders
Step #0:     builders = server.getAllBuilders()
Step #0:   File "/opt/sources/Python-3.5.4/Lib/xmlrpc/client.py", line 1092, in __call__
Step #0:     return self.__send(self.__name, args)
Step #0:   File "/opt/sources/Python-3.5.4/Lib/xmlrpc/client.py", line 1432, in __request
Step #0:     verbose=self.__verbose
Step #0:   File "/opt/sources/Python-3.5.4/Lib/xmlrpc/client.py", line 1134, in request
Step #0: …
```

Skip test_xmlrpc_net when building python interpreters

---

scripts/data/Dockerfile.python_compat
scripts/data/dockerignore.python_compat
scripts/gen_dockerfile.py
scripts/gen_dockerfile_test.py
scripts/testdata/hello_world_compat/app.yaml
scripts/testdata/hello_world_compat/main.py
scripts/testdata/hello_world_compat_golden/.dockerignore
scripts/testdata/hello_world_compat_golden/Dockerfile

Add support for python-compat.
This primarily side-steps the logic for python Dockerfile generation, as the compat Dockerfile is static and unchanging.

Python compat

---

python-interpreter-builder/Dockerfile.in

We never started using these packages, and have a different internal
plan for packaging in the future.

Stop building Debian packages.

---

build.sh
cloudbuild_test.yaml
python-interpreter-builder/Dockerfile.in
python-interpreter-builder/scripts/build-python-3.4.sh
runtime-image/Dockerfile.in
runtime-image/resources/apt-packages.txt
tests/license-test/license-test.yaml
tests/no-virtualenv/no-virtualenv.yaml
tests/virtualenv/virtualenv_default.yaml
tests/virtualenv/virtualenv_python27.yaml
tests/virtualenv/virtualenv_python34.yaml

This requires building Python 3.4 from source, so we do that.
Future changes may add support for other OS base images, such as Debian 9 and Ubuntu 18.  We don't support arbitrary OS base images in general, so it's an enumerated list.

Add support for using Ubuntu 16 as a base instead of Debian 8

---

RELEASING.md
build.sh
cloudbuild.yaml
cloudbuild_interpreters.yaml
runtime-image/Dockerfile.in

This makes it much faster to build runtime images.

Split the runtime release into an interpreter and a runtime build.

---

runtime-image/resources/requirements.txt

Pin pip to 9.0.3. Newer versions conflict with the OS installed package.

---

README.md

I had to dig around in `scripts/gen_dockerfile.py` and `scripts/data/Dockerfile.virtualenv.template` to figure this out after copy-pasting from the README.
It's sort of strange that the default is python2.7, but I wasn't sure if we wanted to change that in the sample.

Document how to use Dockerfile with python3

---

build.sh
runtime-image/Dockerfile.in
runtime-image/resources/apt-packages.txt

Installing pip2.7 via apt-get no longer produces a usable or upgradeable pip.  Installing directly from bootstrap.pypa.io

Fixing build error for python2.7 pip
