Dockerfile

Fixes #16
This bumps or base image size to 694mb

Adding scipy dependencies.

---

.travis.yml
Dockerfile
README.md
tests/no-virtualenv/Dockerfile
tests/virtualenv/Dockerfile

Adding tests for virtualenv usage.

Adding tests for virtualenv usage

---

Dockerfile
tests/python3-libraries/Dockerfile
tests/virtualenv/Dockerfile

Add /opt/python3.5/bin to $PATH

---

build.sh
tests/integration/Dockerfile.in
tests/integration/app.yaml
tests/integration/requirements.txt
tests/integration/server.py

~~**As of 12/7/16, this code is a work in progress.**~~
This is a preliminary attempt at a sample integration test application, which will fulfill the specification for the GCP integration testing framework (once complete).
See https://github.com/GoogleCloudPlatform/runtimes-common/pull/73 for more details.
@dlorenc @duggelz @jonparrott

Integration Test Sample Application

---

Makefile

Do not cache Docker layers and base images by default

---

Dockerfile
python-interpreter-builder/Dockerfile

Fix Docker base image names

---

local-cloudbuild.py

Supports just enough Container Builder functionality to build this image.

Add tool to run cloudbuild.yaml steps locally.

---

tests/integration/server.py

@dlorenc @duggelz 
https://github.com/GoogleCloudPlatform/runtimes-common/pull/129

add sample custom integration test

---

scripts/local_cloudbuild.py
scripts/local_cloudbuild_test.py
scripts/testdata/cloudbuild_builtin_substitutions.yaml
scripts/testdata/cloudbuild_ok.yaml
scripts/testdata/cloudbuild_ok.yaml_golden.sh
scripts/testdata/cloudbuild_user_substitutions.yaml

Container Builder substitutions:
https://cloud.google.com/container-builder/docs/api/build-requests#substitutions

Support the --substitutions flag as per 'gcloud container builds submit'

---

runtime-image/Dockerfile.in
tests/benchmark/Dockerfile.in
tests/benchmark/benchmark_between_releases.sh
tests/google-cloud-python-system/run_system_tests.sh
tests/google-cloud-python/run_unit_tests.sh
tests/python3-libraries/python3-libraries.yaml
tests/virtualenv/virtualenv_python36.yaml

Add Python 3.6 to the PATH.  Enable tests and benchmarking.

Enable Python 3.6 in the base runtime image

---

nox.py

Basically just needed to use the latest version of our tools.

Fix the requirements updating script

---

python-interpreter-builder/scripts/build-python-3.5.sh
python-interpreter-builder/scripts/build-python-3.6.sh

Run Python self-tests when building interpreter

---

runtime-image/Dockerfile.in
runtime-image/resources/apt-packages.txt
runtime-image/resources/requirements.txt

Fixes #94 #152 
CC @jonparrott @kyleobrien91

Update pip, setuptools, virtualenv when we build the base runtime image.

---

tests/integration/server.py

This is to accommodate the changes in https://github.com/GoogleCloudPlatform/runtimes-common/pull/315.

expose /environment endpoint for gke tests

---

tests/integration/server.py

This will enable running integration tests in GKE.

return string instead of bool in integration test sample app env handler

---

builder/python-staging.yaml

Copied from https://github.com/GoogleCloudPlatform/python-runtime/blob/master/builder/python-latest.yaml

Add Runtime Builder template file for "staging" tag.

---

RELEASING.md
build.sh

`gcloud container builds *` is now `gcloud builds *`
`container-builder-local` is now `cloud-build-local`

Update to new GCB commands.

---

python-interpreter-builder/scripts/build-python-3.6.sh
tests/no-virtualenv/no-virtualenv.yaml
tests/virtualenv/virtualenv_python36.yaml

Bump Python 3.6.6 to 3.6.7

---

scripts/deploy_check.sh
scripts/integration-test.sh
scripts/release.sh

Adding build scripts for creating and testing images

Adding build scripts

---

scripts/release.sh

Remove extraneous source command

Fixing release script

---

tests/no-virtualenv/no-virtualenv.yaml
tests/virtualenv/virtualenv_python37.yaml

Update tests to point to new python version

Fixing test

---

runtime-image/resources/requirements.txt

We're going to attempt an upgrade of pip to version 10.0.1 and try to avoid the problem in https://github.com/pypa/pip/issues/5240

Attempting upgrade of pip version

---

runtime-image/resources/requirements.txt

attempting pip upgrade to 20.0.2

Latest pip is actually 20.0.2

---

builder/gen-dockerfile/Dockerfile.in

My change to remove /env/bin/pip was incorrect

Use virtualenv pip
